using System.Text;
using MondayBrief.Core.Alerts;
using MondayBrief.Core.Entities;
using MondayBrief.Core.Kpis;
namespace MondayBrief.Core.Ai;

/// <summary>
/// The only things the model can do. It chooses a tool and arguments; this class runs the query and
/// returns rounded, source-stamped numbers. No SQL is ever generated by the model.
/// </summary>
public sealed class BusinessTools(KpiService kpis, AlertService alerts)
{
    public const string GetMetric = "get_metric";
    public const string ComparePeriods = "compare_periods";
    public const string TopProducts = "top_products";
    public const string ListAlerts = "list_alerts";

    /// <summary>Products needs this many units in the baseline window before they can be ranked.</summary>
    public const int MinUnitsForRanking = KpiService.MinUnitsForRanking;

    private static readonly string[] Metrics = ["revenue", "orders", "aov", "sessions", "conversion"];
    private static readonly string[] Channels = ["all", "instore", "online"];

    public async Task<ToolResult> GetMetricAsync(string metric, DateOnly start, DateOnly end, string? channel = null, CancellationToken cancellationToken = default)
    {
        if (Validate(GetMetric, metric, channel, start, end) is { } failure)
        {
            return failure;
        }

        if (await OutsideWindow(GetMetric, start, end, cancellationToken) is { } windowError)
        {
            return windowError;
        }

        var value = await ValueOf(metric, new DateRange(start, end), channel, cancellationToken);

        return ToolResult.Success(GetMetric, new MetricValue(
            metric.ToLowerInvariant(),
            Normalize(channel),
            start,
            end,
            value,
            UnitOf(metric)));
    }

    public async Task<ToolResult> ComparePeriodsAsync(
        string metric,
        DateOnly periodAStart, DateOnly periodAEnd,
        DateOnly periodBStart, DateOnly periodBEnd,
        string? channel = null,
        CancellationToken cancellationToken = default)
    {
        if (Validate(ComparePeriods, metric, channel, periodAStart, periodAEnd) is { } failureA)
        {
            return failureA;
        }

        if (Validate(ComparePeriods, metric, channel, periodBStart, periodBEnd) is { } failureB)
        {
            return failureB;
        }

        if (await OutsideWindow(ComparePeriods, periodAStart, periodAEnd, cancellationToken) is { } windowA)
        {
            return windowA;
        }

        if (await OutsideWindow(ComparePeriods, periodBStart, periodBEnd, cancellationToken) is { } windowB)
        {
            return windowB;
        }

        var a = await ValueOf(metric, new DateRange(periodAStart, periodAEnd), channel, cancellationToken);
        var b = await ValueOf(metric, new DateRange(periodBStart, periodBEnd), channel, cancellationToken);

        // The model must never do this subtraction itself: the number check only matches tool output.
        var change = Math.Round(b - a, 2, MidpointRounding.AwayFromZero);
        var changePct = a == 0
            ? (double?)null
            : Math.Round((double)(100m * (b - a) / a), 1, MidpointRounding.AwayFromZero);
        
        return ToolResult.Success(ComparePeriods, new PeriodComparison(
            metric.ToLowerInvariant(),
            Normalize(channel),
            new PeriodValue(periodAStart, periodAEnd, a),
            new PeriodValue(periodBStart, periodBEnd, b),
            change,
            changePct,
            UnitOf(metric)));
    }

    public async Task<ToolResult> TopProductsAsync(int n, DateOnly start, DateOnly end, string direction = "top", CancellationToken cancellationToken = default)
    {
        var normalizedDirection = (direction ?? "top").Trim().ToLowerInvariant();
        if (normalizedDirection != "top" && normalizedDirection != "declining")
        {
            return ToolResult.Failure(TopProducts, $"Direction '{direction}' is not available. Use 'top' or 'declining'.");
        }

        if (n is < 1 or > 20)
        {
            return ToolResult.Failure(TopProducts, "n must be between 1 and 20.");
        }

        if (start > end)
        {
            return ToolResult.Failure(TopProducts, $"Start date {start:yyyy-MM-dd} is after end date {end:yyyy-MM-dd}.");
        }

        if (await OutsideWindow(TopProducts, start, end, cancellationToken) is { } windowError)
        {
            return windowError;
        }

        var range = new DateRange(start, end);
        var current = await kpis.GetProductTotalsAsync(range, cancellationToken);

        if (normalizedDirection == "top")
        {
            var rows = current
                .OrderByDescending(p => p.RevenueCents)
                .ThenBy(p => p.Sku, StringComparer.Ordinal)
                .Take(n)
                .Select(p => new ProductRow(p.Sku, p.Name, Money(p.RevenueCents), p.Units, null, null))
                .ToList();

            return ToolResult.Success(TopProducts, new ProductRanking("top", start, end, null, null, 0, rows));
        }

        var previousRange = range.Previous();
        var previous = await kpis.GetProductTotalsAsync(previousRange, cancellationToken);
        var currentBySku = current.ToDictionary(p => p.Sku, StringComparer.Ordinal);

        var declines = previous
            .Where(p => p.Units >= MinUnitsForRanking)
            .Select(p =>
            {
                var now = currentBySku.TryGetValue(p.Sku, out var row) ? row: null;
                var units = now?.Units ?? 0;
                return new ProductRow(
                    p.Sku,
                    p.Name,
                    Money(now?.RevenueCents ?? 0),
                    units,
                    p.Units,
                    Math.Round(100.0 * (units - p.Units) / p.Units, 1, MidpointRounding.AwayFromZero));
            })
            .Where(r => r.ChangePct < 0)
            .OrderBy(r => r.ChangePct)
            .ThenBy(r => r.Sku, StringComparer.Ordinal)
            .Take(n)
            .ToList();

        return ToolResult.Success(TopProducts, new ProductRanking(
            "declining", start, end, previousRange.Start, previousRange.End, MinUnitsForRanking, declines));
    }

    private async Task<decimal> ValueOf(string metric, DateRange range, string? channel, CancellationToken cancellationToken)
    {
        var channelId = Normalize(channel) switch
        {
            "instore" => ChannelIds.InStore,
            "online" => ChannelIds.Online,
            _ => (int?)null,
        };

        var totals = await kpis.GetTotalsAsync(range, channelId, cancellationToken);

        return metric.ToLowerInvariant() switch
        {
            "revenue" => Money(totals.RevenueCents),
            "orders" => totals.Orders,
            "aov" => Math.Round(totals.AverageOrderValueCents / 100m, 2, MidpointRounding.AwayFromZero),
            "sessions" => totals.Sessions,
            "conversion" => Math.Round((decimal)totals.ConversionPct, 2, MidpointRounding.AwayFromZero),
            _ => 0m,
        };
    }

    private ToolResult? Validate(string tool, string metric, string? channel, DateOnly start, DateOnly end)
    {
        var normalizedMetric = (metric ?? string.Empty).Trim().ToLowerInvariant();
        if (!Metrics.Contains(normalizedMetric))
        {
            return ToolResult.Failure(tool,
                $"Metric '{metric}' is not available. This dataset has: {string.Join(", ", Metrics)}. " +
                "There is no cost or profit data.");
        }

        var normalizedChannel = Normalize(channel);
        if (!Channels.Contains(normalizedChannel))
        {
            return ToolResult.Failure(tool, $"Channel '{channel}' is not available. Use instore, online, or leave it out.");
        }

        if (normalizedChannel != "all" && normalizedMetric is "sessions" or "conversion")
        {
            return ToolResult.Failure(tool,
                $"{normalizedMetric} cannot be filtered by channel: web analytics only covers the online store.");
        }

        if (start > end)
        {
            return ToolResult.Failure(tool, $"Start date {start:yyyy-MM-dd} is after end date {end:yyyy-MM-dd}.");
        }

        return null;
    }

    /// <summary>
    /// Refuses dates the data does not cover. Silently returning zeros would let the model report a 
    /// collapse that never happened.
    /// </summary>
    private async Task<ToolResult?> OutsideWindow(string tool, DateOnly start, DateOnly end, CancellationToken cancellationToken)
    {
        var window = await kpis.GetDataWindowAsync(cancellationToken);
        if (window is null)
        {
            return ToolResult.Failure(tool, "No data has been ingested yet.");
        }

        if (start < window.Value.Start || end > window.Value.End)
        {
            return ToolResult.Failure(tool,
                $"Requested {start:yyyy-MM-dd} to {end:yyyy-MM-dd}, but data only covers " +
                $"{window.Value.Start:yyyy-MM-dd} to {window.Value.End:yyyy-MM-dd}.");
        }

        return null;
    } 

    /// <summary>
    /// Alerts as of the demo's today, or over an explicit window when both dates are supplied.
    /// </summary>
    public async Task<ToolResult> ListAlertsAsync(
        DateOnly asOf, DateOnly? start = null, DateOnly? end = null, CancellationToken cancellationToken = default)
    {
        if (start is null != end is null)
        {
            return ToolResult.Failure(ListAlerts, "Supply both start and end dates, or neither.");
        }

        if (start is { } from && end is { } to)
        {
            if (from > to)
            {
                return ToolResult.Failure(ListAlerts, $"Start date {from:yyyy-MM-dd} is after end date {to:yyyy-MM-dd}.");
            }

            if (await OutsideWindow(ListAlerts, from, to, cancellationToken) is { } windowError)
            {
                return windowError;
            }

            var triggered = await alerts.EvaluateWindowAsync(new DateRange(from, to), cancellationToken);
            return ToolResult.Success(ListAlerts, new AlertList(from, to, triggered));
        }

        var current = await alerts.EvaluateAsOfAsync(asOf, cancellationToken);
        return ToolResult.Success(ListAlerts, new AlertList(null, null, current));
    }

    private static string Normalize(string? channel) => 
        string.IsNullOrWhiteSpace(channel) ? "all" : channel.Trim().ToLowerInvariant();
    
    private static decimal Money(long cents) => Math.Round(cents / 100m, 2, MidpointRounding.AwayFromZero);

    private static string UnitOf(string metric) => metric.ToLowerInvariant() switch
    {
        "revenue" or "aov" => "currency",
        "conversion" => "percent",
        _ => "number",
    };
}