// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MondayBrief.Core.Data;

#nullable disable

namespace MondayBrief.Core.Data.Migrations
{
    [DbContext(typeof(MondayBriefDbContext))]
    [Migration("20260916134241_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("MondayBrief.Core.Entities.AlertRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("MinBaseline")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<double>("Threshold")
                        .HasColumnType("REAL");

                    b.Property<int>("WindowDays")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("AlertRules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsEnabled = true,
                            Key = "weekly-revenue-drop",
                            Kind = "RevenueChangePct",
                            MinBaseline = 0,
                            Name = "Weekly revenue down more than 20%",
                            Threshold = -20.0,
                            WindowDays = 7
                        },
                        new
                        {
                            Id = 2,
                            IsEnabled = true,
                            Key = "conversion-below-2pct",
                            Kind = "ConversionRateBelow",
                            MinBaseline = 500,
                            Name = "7-day online conversion below 2%",
                            Threshold = 2.0,
                            WindowDays = 7
                        },
                        new
                        {
                            Id = 3,
                            IsEnabled = true,
                            Key = "product-units-drop",
                            Kind = "ProductUnitsChangePct",
                            MinBaseline = 60,
                            Name = "Product units down more than 30% over 4 weeks",
                            Threshold = -30.0,
                            WindowDays = 28
                        });
                });

            modelBuilder.Entity("MondayBrief.Core.Entities.Brief", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RenderedText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WeekStart")
                        .IsUnique();

                    b.ToTable("Briefs");
                });

            modelBuilder.Entity("MondayBrief.Core.Entities.Channel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Channels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "InStore",
                            Name = "In-store"
                        },
                        new
                        {
                            Id = 2,
                            Code = "Online",
                            Name = "Online store"
                        });
                });

            modelBuilder.Entity("MondayBrief.Core.Entities.DailyTraffic", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("PageViews")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sessions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Users")
                        .HasColumnType("INTEGER");

                    b.HasKey("Date");

                    b.ToTable("DailyTraffic", (string)null);
                });

            modelBuilder.Entity("MondayBrief.Core.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PlacedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long>("SubtotalCents")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("BusinessDate", "ChannelId");

                    b.HasIndex("SourceSystem", "ExternalId")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MondayBrief.Core.Entities.OrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("LineTotalCents")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UnitPriceCents")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderLines");
                });

            modelBuilder.Entity("MondayBrief.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("ListPriceCents")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SoldOnline")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("MondayBrief.Core.Entities.Order", b =>
                {
                    b.HasOne("MondayBrief.Core.Entities.Channel", "Channel")
                        .WithMany("Orders")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("MondayBrief.Core.Entities.OrderLine", b =>
                {
                    b.HasOne("MondayBrief.Core.Entities.Order", "Order")
                        .WithMany("Lines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MondayBrief.Core.Entities.Product", "Product")
                        .WithMany("OrderLines")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MondayBrief.Core.Entities.Channel", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("MondayBrief.Core.Entities.Order", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("MondayBrief.Core.Entities.Product", b =>
                {
                    b.Navigation("OrderLines");
                });
#pragma warning restore 612, 618
        }
    }
}
